# Generated by Django 5.2.1 on 2025-06-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_agree_marketing_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="agree_privacy",),
    ]
