# Generated by Django 5.2.1 on 2025-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_agree_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="plan_type",
            field=models.CharField(default="Free", max_length=30),
        ),
    ]
